services:
  noetic:
    # image: osrf/ros:noetic-desktop
    container_name: noetic
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        GROUP_ID: ${GROUP_ID}
        GROUP_NAME: ${GROUP_NAME}
        WORKSPACE: ${WORKSPACE}
    network_mode: host # Mandatory for GUI
    runtime: nvidia
    devices:
      - /dev/dri/
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DISPLAY=$DISPLAY
    volumes:
      - $HOME/.Xauthority:$HOME/.Xauthority:ro
      - ./catkin_ws:/catkin_ws
    stdin_open: true
    tty: true
    command: /bin/bash -c "source /opt/ros/noetic/setup.bash && roscore"
