services:
  humble:
    # image: osrf/ros:humble-desktop
    container_name: humble
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        GROUP_ID: ${GROUP_ID}
        GROUP_NAME: ${GROUP_NAME}
        WORKSPACE: ${WORKSPACE}
    network_mode: host # Mandatory for GUI
    runtime: nvidia
    devices:
      - /dev/dri/
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DISPLAY=$DISPLAY
      - TERM=xterm-256color
    volumes:
      - $HOME/.Xauthority:$HOME/.Xauthority:ro
      - ./catkin_ws:/catkin_ws
    stdin_open: true
    tty: true
    command: tail -f /dev/null
